sudo: true
language: go
stages:
- test
- name: release
  if: tag IS present
jobs:
  include:
  - stage: test
    script:
    - go get golang.org/x/lint/golint
    - golint
  - script: go test -v
  - stage: release
    env:
    - DOCKER_USERNAME=phillebaba
    services: docker
    script:
    - git clone git://github.com/docker/buildx
    - cd buildx
    - make install
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker run --rm --privileged multiarch/qemu-user-static:register
    - bin/buildx build --platform=linux/arm/v7 --push -t phillebaba/bike-tracker ..

