sudo: true
language: go

before_install:
  - docker --version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

stages:
- test
- release

jobs:
  include:
  - stage: test
    script:
    - go get golang.org/x/lint/golint
    - golint
  - stage: release
    env:
    - DOCKER_USERNAME=phillebaba
    services: docker
    script:
    - git clone git://github.com/docker/buildx
    - cd buildx
    - make install
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker run --rm --privileged multiarch/qemu-user-static:register
    - bin/buildx build --platform=linux/arm/v7 --push -t phillebaba/bike-tracker ..

