sudo: true
language: go

stages:
  - test
  - build-push
  - manifest

jobs:
  include:
    - stage: test
      env:
      script:
        - go get golang.org/x/lint/golint
        - golint

    - stage: build-push
      env: ARCH=amd64
      services: docker
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register
        - env GOOS=linux GOARCH=${ARCH} go build -o bike-touring-tracker-${ARCH} cmd/server/main.go
        - docker build --build-arg ARCH=${ARCH} -t $DOCKER_USERNAME/bike-touring-tracker:${TRAVIS_BRANCH}-linux-${ARCH} .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/bike-touring-tracker:${TRAVIS_BRANCH}-linux-${ARCH}

    - stage: build-push
      env: ARCH=arm64
      services: docker
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register
        - env GOOS=linux GOARCH=${ARCH} go build -o bike-touring-tracker-${ARCH} cmd/server/main.go
        - docker build --build-arg ARCH=${ARCH} -t $DOCKER_USERNAME/bike-touring-tracker:${TRAVIS_BRANCH}-linux-${ARCH} .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/bike-touring-tracker:${TRAVIS_BRANCH}-linux-${ARCH}

    - stage: build-push
      env: ARCH=arm
      services: docker
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register
        - env GOOS=linux GOARCH=${ARCH} go build -o bike-touring-tracker-${ARCH} cmd/server/main.go
        - docker build --build-arg ARCH=${ARCH} -t $DOCKER_USERNAME/bike-touring-tracker:${TRAVIS_BRANCH}-linux-${ARCH} .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/bike-touring-tracker:${TRAVIS_BRANCH}-linux-${ARCH}

    - stage: manifest
      env:
      script:
        - wget https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
        - mv manifest-tool-linux-amd64 manifest-tool
        - chmod +x manifest-tool
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - ./manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64
          --template "phillebaba/bike-touring-tracker:${TRAVIS_BRANCH}-OS-ARCH" --target "phillebaba/bike-touring-tracker:${TRAVIS_BRANCH}"
