---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-touring-tracker-deployment
  labels:
    app: bike-touring-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bike-touring-tracker
  template:
    metadata:
      labels:
        app: bike-touring-tracker
    spec:
      containers:
      - name: bike-touring-tracker
        image: phillebaba/bike-touring-tracker:master
        imagePullPolicy: Always
        command: ["/bin/bike-touring-tracker"]
        args:
          - "-postgres-host=$(POSTGRES_SERVICE)"
          - "-postgres-password=$(DB_PASSWORD)"
          - "-admin-password=$(ADMIN_PASSWORD)"
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: btt-secret
              key: admin-password
        - name: GIN_MODE
          value: "release"
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.4-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/db-data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

