---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  db-password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: btt-secret
type: Opaque
stringData:
  admin-password: "password"
