---
apiVersion: v1
kind: Service
metadata:
  name: btt-service
spec:
  selector:
    app: bike-touring-tracker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
